Repository twilio-professional-services/flex-project-template, pull requests merged in 2022-12, with the labels that each got.

#90 Hang Up By and Destination reporting
  README.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/package-lock.json
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/conference/custom-components/ConferenceDialog/ConferenceDialog.tsx
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/README.md
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/enums/hangUpBy.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/actions/CompleteTask.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/actions/HangupCall.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/actions/KickParticipant.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/actions/StartExternalWarmTransfer.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/actions/TransferTask.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/events/pluginsLoaded.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/events/taskCompleted.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/events/taskWrapup.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/helpers/hangUpBy.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/index.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/utils/HangUpByService.ts
  plugin-flex-ts-template-v2/src/flex-hooks/actions/actions.ts
  plugin-flex-ts-template-v2/src/flex-hooks/events/events.ts
  plugin-flex-ts-template-v2/src/types/flex-hooks/Actions.ts
  plugin-flex-ts-template-v2/src/types/manager/CustomServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/types/serverless/twilio-api.ts
  plugin-flex-ts-template-v2/src/types/task-router/Task.ts
  serverless-functions/src/functions/common/twilio-wrappers/conference-participant.private.js
  serverless-functions/src/functions/features/hang-up-by/flex/fetch-conference-participant.js
Labels: ready-for-review

#99 Minor initial bringup improvements
  README.md
  plugin-flex-ts-template-v2/package-lock.json
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/device-manager/custom-components/DeviceManager/DeviceManager.tsx
  plugin-flex-ts-template-v2/src/feature-library/device-manager/flex-hooks/paste-elements/index.ts
  plugin-flex-ts-template-v2/src/flex-hooks/paste-elements/paste-elements.ts
  scripts/common.js
  scripts/populate-missing-placeholders.js
  scripts/setup-local-environment.js
Labels: ready-for-review

#101 Fix schedule manager localization shortcomings
  plugin-flex-ts-template-v2/package-lock.json
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/custom-components/RuleDataTable/RuleDataTable.tsx
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/custom-components/RuleEditor/RuleEditor.tsx
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/utils/RRuleLanguage.ts
Labels: ready-for-review

#94 Update Paste and use switch in capacity config
  plugin-flex-ts-template-v2/package-lock.json
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/caller-id/custom-components/OutboundCallerIDSelector/OutboundCallerIDSelectorComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-capacity/custom-components/CapacityChannel/CapacityChannel.tsx
Labels: ready-for-review

#102 Reduce plugin size
  .github/workflows/flex_deploy_dev.yaml
  .github/workflows/flex_deploy_prod.yaml
  .github/workflows/flex_deploy_qa.yaml
  .github/workflows/flex_deploy_test.yaml
  plugin-flex-ts-template-v2/package-lock.json
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/custom-components/CallbackAndVoicemail/CallbackAndVoicemail.tsx
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/utils/callback/CallbackService.ts
  plugin-flex-ts-template-v2/src/feature-library/supervisor-capacity/custom-components/CapacityContainer/CapacityContainer.tsx
  plugin-flex-ts-template-v2/src/types/task-router/Task.ts
Labels: ready-for-review

#96 Suppress Flex error during internal calls
  plugin-flex-ts-template-v2/package-lock.json
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/internal-call/flex-hooks/events/pluginsLoaded.ts
  plugin-flex-ts-template-v2/src/feature-library/internal-call/flex-hooks/notifications/InternalCall.ts
  plugin-flex-ts-template-v2/src/flex-hooks/events/events.ts
  plugin-flex-ts-template-v2/src/flex-hooks/notifications/notifications.ts
Labels: ready-for-review

#108 Windows support
  .gitignore
  README.md
  flex-config/package-lock.json
  package-lock.json
  plugin-flex-ts-template-v1/package-lock.json
  plugin-flex-ts-template-v2/package-lock.json
  scripts/common.js
  scripts/remove-features.js
  scripts/rename-template.js
  scripts/select-plugin.js
  scripts/setup-local-environment.js
  scripts/start-local.js
  serverless-functions/package-lock.json
  serverless-schedule-manager/package-lock.json
  web-app-examples/video-app-quickstart/package-lock.json
Labels: ready-for-review

#105 Fix endConferenceOnExit being wrong with XWT
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/conference/custom-components/ConferenceMonitor/ConferenceMonitor.tsx
Labels: ready-for-review

#97 Fix recording internal calls with dual-channel
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/flex-hooks/events/taskAccepted.ts
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/dualChannelHelper.ts
  plugin-flex-ts-template-v2/src/feature-library/pause-recording/flex-hooks/components/CallCanvasActions.tsx
Labels: question, ready-for-review

#109 Insights never works on localhost- restore sanity
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/flex-hooks/notifications/index.ts
Labels: ready-for-review

#110 Auto version bump
  .github/pull_request_template.md
  .github/template_files/flex_deploy_dev.yaml
  .github/template_files/flex_deploy_prod.yaml
  .github/template_files/flex_deploy_qa.yaml
  .github/template_files/flex_deploy_test.yaml
  .github/workflows/bump_version_plugin_v1.yaml
  .github/workflows/bump_version_plugin_v2.yaml
  .github/workflows/flex_deploy_dev.yaml
  .github/workflows/flex_deploy_prod.yaml
  .github/workflows/flex_deploy_qa.yaml
  .github/workflows/flex_deploy_test.yaml
  plugin-flex-ts-template-v2/README.md
Labels: ready-for-review

#112 Fix version bump branch
  .github/workflows/bump_version_plugin_v1.yaml
  .github/workflows/bump_version_plugin_v2.yaml
Labels: ready-for-review

#114 Commit version bump pre merge instead of after
  .github/workflows/bump_version_plugin_v1.yaml
  .github/workflows/bump_version_plugin_v2.yaml
Labels: ready-for-review

#116 Fix missing line in readme
  README.md
Labels: documentation, ready-for-review

#117 Flex UI 2.0 GA
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/worker-profile-info/WorkerProfileInfo.tsx
  plugin-flex-ts-template-v2/src/feature-library/caller-id/custom-components/OutboundCallerIDSelector/OutboundCallerIDSelectorComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/chat-transfer/custom-components/TransferButton/TransferButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/conference/custom-components/ConferenceButton/ConferenceButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/conference/custom-components/ParticipantActionsButtons/ParticipantActionsButtons.tsx
  plugin-flex-ts-template-v2/src/feature-library/device-manager/custom-components/DeviceManager/DeviceManager.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/IFrameWrapper/IFrameWrapper.tsx
  plugin-flex-ts-template-v2/src/feature-library/internal-call/custom-components/InternalDialpad/InternalDialpad.tsx
  plugin-flex-ts-template-v2/src/feature-library/multi-call/helpers/MultiCallHelper.ts
  plugin-flex-ts-template-v2/src/feature-library/pause-recording/custom-components/PauseRecordingButton/PauseRecordingButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/custom-components/RuleEditor/RuleEditor.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/BargeCoachButtons/SupervisorBargeCoachButtonComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/SupervisorPrivateModeButton/SupervisorPrivateModeButtonComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-capacity/custom-components/CapacityContainer/CapacityContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/custom-components/FreeTextFilter/FreeTextFilter.tsx
Labels: ready-for-review

#123 Pin @twilio-paste/icons to 9.4.0 to fix error
  plugin-flex-ts-template-v2/package.json
Labels: ready-for-review

#124 Fix undefined codecPreferences in multi-call
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/multi-call/helpers/MultiCallHelper.ts
Labels: ready-for-review
