Repository twilio-professional-services/flex-project-template, pull requests merged in 2023-06, with the labels that each got.

#234 Rename callback config to be consistent
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/config.ts
Labels: ready-for-review

#239 Point to conversations from chat-transfer readme
  docs/docs/feature-library/flex-v2/07_chat-transfer.md
Labels: documentation, ready-for-review

#236 Add Admin UI
  .github/template_files/flex_deploy_dev.yaml
  .github/template_files/flex_deploy_prod.yaml
  .github/template_files/flex_deploy_qa.yaml
  .github/template_files/flex_deploy_test.yaml
  .github/workflows/flex_deploy_dev.yaml
  .github/workflows/flex_deploy_prod.yaml
  .github/workflows/flex_deploy_qa.yaml
  .github/workflows/flex_deploy_test.yaml
  docs/docs/feature-library/00_overview.md
  docs/docs/feature-library/flex-v2/admin-ui.md
  docs/docs/setup-guides/01_setup-release-pipeline.md
  docs/static/img/f2/admin-ui/admin-ui.gif
  flex-config/index.js
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/admin-hook.tsx
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/custom-components/ActivityHandlerAdmin/ActivityHandlerAdmin.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/config.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/AdminSideLink/AdminSideLink.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/AdminSideLink/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/AdminView/AdminView.Styles.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/AdminView/AdminView.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/AdminView/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/FeatureCard/FeatureCard.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/FeatureCard/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/FeatureModal/FeatureModal.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/FeatureModal/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/components/SideNav.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/components/ViewCollection.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/notifications/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/paste-elements/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/strings/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/index.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/utils/AdminUiService.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/utils/helpers.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/utils/sync-stream.ts
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/admin-hook.tsx
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/custom-components/ScheduleAdmin/ScheduleAdmin.tsx
  plugin-flex-ts-template-v2/src/types/task-router/Worker.ts
  plugin-flex-ts-template-v2/src/utils/configuration/index.ts
  plugin-flex-ts-template-v2/template-files/feature-template/README.md
  scripts/add-feature.js
  serverless-functions/.boiler-plate-function
  serverless-functions/src/functions/common/twilio-wrappers/configuration.private.js
  serverless-functions/src/functions/common/twilio-wrappers/lookup.private.js
  serverless-functions/src/functions/features/admin-ui/flex/fetch-config.js
  serverless-functions/src/functions/features/admin-ui/flex/update-config.js
Labels: enhancement, ready-for-review

#238 Properly fix activity filter across versions
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/activity-wrapper/ActivityWrapper.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/activity-wrapper/ActivityWrapperComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/activity-wrapper/index.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/flex-hooks/components/MainHeader.tsx
Labels: ready-for-review

#240 Use task/worker attributes within canned responses
  docs/docs/feature-library/flex-v2/05_canned-responses.md
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Response/Response.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/CannedResponsesDropdown.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/components/CRMContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/utils/helpers.ts
Labels: ready-for-review

#244 Separate dual channel and pause recording services
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/flex-hooks/events/taskAccepted.ts
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/DualChannelService.ts
  plugin-flex-ts-template-v2/src/feature-library/pause-recording/helpers/PauseRecordingService.ts
  plugin-flex-ts-template-v2/src/feature-library/pause-recording/helpers/pauseRecordingHelper.ts
Labels: ready-for-review

#241 Enhance enhanced CRM container feature with enhancements
  docs/docs/feature-library/flex-v2/15_enhanced-crm-container.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/config.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/IFrameCRMComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/IFrameWrapper/IFrameWrapper.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/components/CRMContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/utils/helpers.ts
Labels: enhancement, ready-for-review

#245 Park interactions
  docs/docs/feature-library/00_overview.md
  docs/docs/feature-library/flex-v2/localization.md
  docs/docs/feature-library/flex-v2/park-interaction.md
  docs/static/img/f2/park-interaction/park-interaction.gif
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/actions/ParkInteraction.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/config.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/custom-components/ParkButton/ParkButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/custom-components/ParkButton/index.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/components/TaskCanvasHeader.tsx
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/notifications/index.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/strings/index.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/index.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/types/ParkInteractionPayload.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/utils/ParkInteractionService.ts
  serverless-functions/src/functions/common/twilio-wrappers/conversations.private.js
  serverless-functions/src/functions/features/park-interaction/common/unpark-interaction.js
  serverless-functions/src/functions/features/park-interaction/flex/park-interaction.js
Labels: ready-for-review

#178 Feature/keyboard shortcuts
  docs/docs/feature-library/flex-v2/29_keyboard_shortcuts.md
  docs/static/img/f2/keyboard-shortcuts/custom-keyboard-shortcuts.png
  docs/static/img/f2/keyboard-shortcuts/default-keyboard-shortcuts.png
  docs/static/img/f2/keyboard-shortcuts/delete-shortcuts.gif
  docs/static/img/f2/keyboard-shortcuts/disable-shortcuts.gif
  docs/static/img/f2/keyboard-shortcuts/key-throttling.gif
  docs/static/img/f2/keyboard-shortcuts/remap-shortcut.gif
  docs/static/img/f2/keyboard-shortcuts/reset-shortcuts.gif
  docs/static/img/f2/keyboard-shortcuts/settings.gif
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/config.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/DeleteButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/EditButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/KeyCommand.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/KeyboardShortcuts.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/ModalWindow.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/Tabs/CustomKeyboardShortcutsView.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/Tabs/DefaultKeyboardShortcutsView.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/Tabs/Settings.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/SideNavigation/SideNavigationIcon.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/flex-hooks/components/SideNav.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/flex-hooks/components/ViewCollection.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/flex-hooks/strings/index.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/index.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/types/types.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/utils/CustomKeyboardShortcuts.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/utils/KeyboardShortcutsUtil.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/utils/LocalStorageUtil.ts
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/utils/constants.ts
  plugin-flex-ts-template-v2/src/icons/Keyboard.tsx
  plugin-flex-ts-template-v2/tsconfig.json
Labels: ready-for-review

#246 Fix broken link
  docs/docs/feature-library/flex-v2/29_keyboard_shortcuts.md
Labels: ready-for-review

#249 Fix kicking the connecting participant
  plugin-flex-ts-template-v2/src/feature-library/conference/custom-components/ConnectingParticipants/ConnectingParticipants.tsx
Labels: bug, ready-for-review

#250 Chat to video localization and deployment fixes
  .github/template_files/flex_deploy_dev.yaml
  .github/template_files/flex_deploy_prod.yaml
  .github/template_files/flex_deploy_qa.yaml
  .github/template_files/flex_deploy_test.yaml
  .github/workflows/flex_deploy_dev.yaml
  .github/workflows/flex_deploy_prod.yaml
  .github/workflows/flex_deploy_qa.yaml
  .github/workflows/flex_deploy_test.yaml
  docs/docs/feature-library/flex-v2/06_chat-to-video-escalation.md
  plugin-flex-ts-template-v2/src/feature-library/chat-to-video-escalation/custom-components/SwitchToVideo/SwitchToVideo.tsx
  plugin-flex-ts-template-v2/src/feature-library/chat-to-video-escalation/flex-hooks/strings/ChatToVideo.ts
  scripts/common.js
  scripts/populate-missing-placeholders.js
  scripts/setup-local-environment.js
  serverless-functions/.env.dev
  serverless-functions/.env.example
  serverless-functions/.env.prod
  serverless-functions/.env.qa
  serverless-functions/.env.test
  serverless-functions/.gitignore
  serverless-functions/src/functions/features/chat-to-video-escalation/generate-unique-code.js
  web-app-examples/video-app-quickstart/.env.example
  web-app-examples/video-app-quickstart/README.md
Labels: bug, ready-for-review

#248 Use serverless to fetch voicemail with HTTP auth
  docs/docs/feature-library/flex-v2/03_callback-and-voicemail.md
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/custom-components/CallbackAndVoicemail/CallbackAndVoicemail.tsx
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/flex-hooks/strings/Callback.ts
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/utils/callback/CallbackService.ts
  serverless-functions/src/functions/common/twilio-wrappers/programmable-voice.private.js
  serverless-functions/src/functions/features/callback-and-voicemail/flex/fetch-voicemail.js
Labels: ready-for-review

#258 Fix participants tab with worker missing full_name
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantsTab/hooks.ts
Labels: bug, ready-for-review

#259 Fix error with empty sync doc
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/utils/sync/Sync.ts
Labels: ready-for-review

#257 Require admin role to update global config
  serverless-functions/src/functions/features/admin-ui/flex/update-config.js
Labels: ready-for-review

#265 Work around Flex bug with parking
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/actions/ParkInteraction.ts
Labels: ready-for-review

#267 Retry using exponential backoff with full jitter
  plugin-flex-ts-template-v2/src/utils/serverless/ApiService/index.ts
  serverless-functions/src/functions/common/helpers/retry-handler.private.js
Labels: ready-for-review

#272 updating broken links for docs site
  docs/docs/how-it-works/04_plugin-flex-ts-template-v2.md
  docs/docs/setup-guides/00_local-setup-and-use.md
Labels: ready-for-review

#274 fixing release script
  .github/template_files/flex_deploy.yaml
  .github/workflows/flex_deploy.yaml
Labels: ready-for-review

#255 Add custom, translate-able Activities filter
  docs/docs/feature-library/flex-v2/26_teams-view-filters.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/config.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/activitiesFilter.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/flex-hooks/strings/TeamViewQueueFilter.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/flex-hooks/teams-filters/TeamsFilters.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/utils/feature-loader/teams-filters.ts
Labels: ready-for-review

#256 Misc fixes in internal-call
  plugin-flex-ts-template-v2/src/feature-library/internal-call/custom-components/InternalDialpad/InternalDialpad.tsx
Labels: ready-for-review

#254 Add cascading menus to canned responses
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/CannedResponsesDropdown.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/CategorySubMenu.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/components/MessageInputActions.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/paste-elements/index.ts
Labels: ready-for-review
