Repository twilio-professional-services/flex-project-template, pull requests merged in 2023-10, with the labels that each got.

#355 Teams View: Add Tasks Summary by Channel & Team + Agent Activity by Team summary table
  docs/docs/feature-library/teams-view-enhancements.md
  docs/static/img/features/teams-view-enhancements/TeamsViewTaskAndActivitySummary.png
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/queues-view-data-tiles/config.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/config.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/AgentTeamActivityTile/AgentTeamActivityTile.Components.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/AgentTeamActivityTile/AgentTeamActivityTile.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/TaskSummaryTile/TaskSummaryTile.Components.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/TaskSummaryTile/TaskSummaryTile.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/TeamsViewDataTiles/TeamsViewDataTiles.Components.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/TeamsViewDataTiles/TeamsViewDataTiles.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/flex-hooks/components/TeamsViewColumns.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/flex-hooks/components/TeamsViewTiles.Styles.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/flex-hooks/components/TeamsViewTiles.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/flex-hooks/paste-elements/index.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/flex-hooks/strings/index.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/types/index.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/utils/WorkerDataUtil.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/utils/helpers.ts
Labels: enhancement, ready-for-review

#369 Updates for Flex Plugins CLI 6.2.0
  package.json
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/webpack.config.js
Labels: bug, ready-for-review

#370 Remove material icons to reduce bundle size
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/flex-hooks/channels/Callback.tsx
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/flex-hooks/channels/Voicemail.tsx
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/flex-hooks/paste-elements/index.ts
Labels: ready-for-review

#360 Add option to overwrite environment config
  scripts/common/fill-replacements.mjs
  scripts/common/save-appconfig.mjs
  scripts/setup-environment.mjs
Labels: ready-for-review

#364 Add ‘from’ attribute for callbacks
  serverless-functions/src/functions/features/callback-and-voicemail/common/callback-operations.private.js
Labels: ready-for-review

#363 Further enhance CRM container with extensible tabs
  docs/docs/feature-library/enhanced-crm-container.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/custom-action/openFeatureSettings.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/config.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Response/Response.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/actions/CRMContainerLoaded.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/components/CRMContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/config.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/IFrameCRMComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/IFrameWrapper/IFrameWrapper.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/IFrameWrapper/IFrameWrapperStyles.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/IFrameWrapper/index.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMContainer/index.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMTab/IFrameCRMTab.Styles.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMTab/IFrameCRMTab.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/IFrameCRMTab/index.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/TabbedCRMContainer/TabbedCRMContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/TabbedCRMContainer/index.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/TabbedCRMTask/TabbedCRMTask.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/TabbedCRMTask/index.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/actions/CRMContainerLoaded.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/components/CRMContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/custom-action/loadCRMContainerTabs.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/flex-hooks/paste-elements/index.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/custom-actions/parkInteraction.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/custom-actions/unparkInteraction.ts
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/events/pluginsInitialized.ts
Labels: ready-for-review

#382 Fix activity-skill-filter in 2.4.0
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/activity-wrapper/ActivityWrapper.ts
Labels: ready-for-review

#367 Add new asset to use as default CRM IFrame page
  docs/docs/feature-library/enhanced-crm-container.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/utils/EnhancedCRMService.ts
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/utils/helpers.ts
  serverless-functions/src/assets/features/enhanced-crm-container/index.html
  serverless-functions/src/assets/features/enhanced-crm-container/noActiveTask.png
Labels: ready-for-review

#372 Reduce size of lodash and Paste
  plugin-flex-ts-template-v2/.eslintrc.js
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/custom-components/ActivityHandlerAdmin/ActivityHandlerAdmin.tsx
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/custom-components/pending-activity/PendingActivityComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/utils/AgentActivities.ts
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/AdminView/AdminView.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/FeatureCard/FeatureCard.tsx
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/FeatureModal/FeatureModal.tsx
  plugin-flex-ts-template-v2/src/feature-library/callback-and-voicemail/custom-components/CallbackAndVoicemail/CallbackAndVoicemail.tsx
  plugin-flex-ts-template-v2/src/feature-library/chat-to-video-escalation/custom-components/VideoRoom/VideoRoom.tsx
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantTabLabel/ParticipantTabLabel.tsx
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantsTab/InvitedParticipants/InvitedParticipant/InvitedParticipant.tsx
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantsTab/InvitedParticipants/InvitedParticipants.tsx
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantsTab/Participants.tsx/Participant/Participant.tsx
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantsTab/Participants.tsx/Participants.tsx
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantsTab/ParticipantsTab.tsx
  plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/CommonDirectoryComponents.tsx
  plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/ExternalDirectoryTab.tsx
  plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/ExternalItem.tsx
  plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/QueueDirectoryTab.tsx
  plugin-flex-ts-template-v2/src/feature-library/custom-transfer-directory/custom-components/QueueItem.tsx
  plugin-flex-ts-template-v2/src/feature-library/device-manager/custom-components/DeviceManager/DeviceManager.tsx
  plugin-flex-ts-template-v2/src/feature-library/dispositions/custom-components/DispositionTab/DispositionTab.tsx
  plugin-flex-ts-template-v2/src/feature-library/internal-call/custom-components/InternalDialpad/InternalDialpad.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/DeleteButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/EditButton.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/KeyboardShortcuts.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/ModalWindow.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/Tabs/CustomKeyboardShortcutsView.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/Tabs/DefaultKeyboardShortcutsView.tsx
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/custom-components/KeyboardShortcuts/Tabs/Settings.tsx
  plugin-flex-ts-template-v2/src/feature-library/localization/custom-components/LanguageSelector/LanguageSelector.tsx
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/custom-components/ParkView/ParkView.tsx
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/custom-components/ParkView/ParkViewTable.tsx
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/custom-components/ParkView/ParkViewTableBodyWrapper.tsx
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/custom-components/ScheduleAdmin/ScheduleAdmin.tsx
  plugin-flex-ts-template-v2/src/feature-library/send-audio-rec-file/custom-components/AudioRecorderPanel/AudioRecorderPanel.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/AgentAssistanceButton/AgentAssistanceButtonComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/AgentAssistanceTeamsIcon/AgentAssistanceTeamsIcon.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/BargeCoachButtons/SupervisorBargeCoachButtonComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/CoachingStatusPanel/CoachingStatusPanelComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/SupervisorAlertButton/SupervisorAlertButtonComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/SupervisorMonitorPanel/SupervisorMonitorPanelComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/custom-components/SupervisorPrivateModeButton/SupervisorPrivateModeButtonComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-complete-reservation/custom-components/SupervisorCompleteReservation/SupervisorCompleteReservation.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/AgentTeamActivityTile/AgentTeamActivityTile.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/custom-components/TaskSummaryTile/TaskSummaryTile.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/agentSkillsFilter.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/queueNoWorkerDataFilter.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/queueWorkerDataFilter.tsx
  plugin-flex-ts-template-v2/src/utils/configuration/index.ts
  plugin-flex-ts-template-v2/src/utils/feature-loader/css-overrides.ts
  plugin-flex-ts-template-v2/src/utils/serverless/TaskRouter/TaskRouterService.ts
  plugin-flex-ts-template-v2/test-utils/flex-redux.ts
  plugin-flex-ts-template-v2/test-utils/flex-service-configuration.ts
Labels: ready-for-review

#374 Enhance sample callback workflow with retry delay
  docs/docs/feature-library/callback-and-voicemail.md
  infra-as-code/terraform/taskrouter/callback.json
Labels: ready-for-review

#377 Update activity handler to use logger
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/SetActivity.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/StartOutboundCall.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskAccepted.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskCanceled.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskCompleted.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskRejected.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskRescinded.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskTimeout.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskWrapup.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/workerActivityUpdated.ts
Labels: ready-for-review

#365 Pre-configure API key/secret and local flex-config for easier deploy
  docs/docs/04_package-overview.md
  docs/docs/building/deployment/local-deployment.md
  docs/docs/building/template-utilities/configuration.md
  flex-config/.env.example
  scripts/common/constants.mjs
  scripts/common/fill-replacements.mjs
  scripts/common/get-account.mjs
  scripts/print-profile-account.mjs
  scripts/setup-environment.mjs
Labels: documentation, ready-for-review

#384 Adding check for non-existent object
  plugin-flex-ts-template-v2/src/feature-library/admin-ui/custom-components/AdminView/AdminView.tsx
Labels: bug

#385 Fix for repeated terraform deploys
  .github/workflows/terraform_deploy.yaml
  infra-as-code/state/import_internal_state.sh
  infra-as-code/state/pull_state.sh
Labels: bug

#388 Fix minor errors
  plugin-flex-ts-template-v2/src/feature-library/enhanced-crm-container/custom-components/TabbedCRMTask/TabbedCRMTask.tsx
  plugin-flex-ts-template-v2/src/utils/feature-loader/index.ts
Labels: ready-for-review

#375 Datadog log integration
  docs/docs/feature-library/00_overview.md
  docs/docs/feature-library/datadog-log-integration.md
  docs/static/img/features/datadog-log-integration/settings.png
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/.prettierignore
  plugin-flex-ts-template-v2/src/feature-library/datadog-log-integration/config.ts
  plugin-flex-ts-template-v2/src/feature-library/datadog-log-integration/destination/Datadog.ts
  plugin-flex-ts-template-v2/src/feature-library/datadog-log-integration/flex-hooks/logger/index.ts
  plugin-flex-ts-template-v2/src/feature-library/datadog-log-integration/index.ts
  plugin-flex-ts-template-v2/src/feature-library/datadog-log-integration/types/ServiceConfiguration.ts
Labels: ready-for-review

#386 Rename Template Fixes for redux namespace and serverless domain mismatch
  infra-as-code/state/config.sh
  infra-as-code/state/delete.sh
  infra-as-code/state/import_internal_state.sh
  infra-as-code/state/pull_state.sh
  infra-as-code/state/push_state.sh
  infra-as-code/terraform/environments/default/main.tf
  infra-as-code/terraform/environments/default/outputs.tf
  infra-as-code/terraform/environments/default/variables.tf
  infra-as-code/terraform/modules/studio/main.tf
  infra-as-code/terraform/modules/studio/outputs.tf
  infra-as-code/terraform/modules/studio/variables.tf
  infra-as-code/terraform/modules/taskrouter/activities.tf
  infra-as-code/terraform/modules/taskrouter/outputs.tf
  infra-as-code/terraform/modules/taskrouter/task_queues.tf
  infra-as-code/terraform/modules/taskrouter/workflows.tf
  plugin-flex-ts-template-v2/src/utils/state/index.ts
  scripts/common/constants.mjs
  scripts/remove-features.mjs
  scripts/rename-template.mjs
Labels: bug

#394 Dark mode fixes for teams view features
  plugin-flex-ts-template-v2/src/feature-library/attribute-viewer/custom-components/WorkerAttributes/WorkerAttributes.Styles.tsx
  plugin-flex-ts-template-v2/src/feature-library/supervisor-capacity/custom-components/CapacityContainer/CapacityContainerStyles.tsx
Labels: ready-for-review

#392 Document CI options
  docs/docs/building/deployment/ci-deployment.md
Labels: documentation, ready-for-review

#389 Add uninstall script option
  docs/docs/building/template-utilities/configuration.md
  scripts/common/install-packages.mjs
  scripts/setup-environment.mjs
Labels: ready-for-review

#390 Remove duplicate workflow
  .github/workflows/terraform_deploy_only.yaml
Labels: ready-for-review

#399 correcting availability status for "On A Task" and "Wrap Up" activites
  infra-as-code/terraform/modules/taskrouter/activities.tf
Labels: ready-for-review

#398 Update callback music
  serverless-functions/src/assets/features/callback-and-voicemail/wait-experience-music-30s.mp3
  serverless-functions/src/functions/features/callback-and-voicemail/studio/wait-experience.protected.js
Labels: ready-for-review

#405 Use Node 18 for serverless
  serverless-functions/.twilioserverlessrc
  serverless-functions/package.json
  serverless-schedule-manager/.twilioserverlessrc
  serverless-schedule-manager/package.json
Labels: ready-for-review

#395 Environment setup enhancements for Terraform
  .github/workflows/flex_deploy.yaml
  .github/workflows/terraform_deploy.yaml
  .gitignore
  docs/docs/building/template-utilities/configuration.md
  infra-as-code/state/import_internal_state.sh
  infra-as-code/state/push_state.sh
  infra-as-code/terraform/environments/default/example.tfvars
  infra-as-code/terraform/environments/default/main.tf
  infra-as-code/terraform/environments/default/variables.tf
  package.json
  scripts/common/fetch-cli.mjs
  scripts/common/fill-replacements.mjs
  scripts/common/print-replacements.mjs
  scripts/config/mappings.json
  scripts/remove-features.mjs
  scripts/setup-environment.mjs
  serverless-functions/package.json
  serverless-schedule-manager/package.json
Labels: ready-for-review

#406 Revert cli downgrade
  plugin-flex-ts-template-v2/package.json
Labels: ready-for-review

#403 Configure dependabot for GitHub Actions
  .github/dependabot.yml
Labels: ready-for-review

#413 Fix Access-Control-Allow-Methods header
  serverless-functions/src/functions/common/helpers/function-helper.private.js
Labels: ready-for-review
