Repository twilio-professional-services/flex-project-template, pull requests merged in 2023-07, with the labels that each got.

#281 Use documented URL format, reduce API requests
  .gitignore
  docs/docs/setup-guides/00_deploy-to-hosted-flex.md
  docs/docs/setup-guides/06_add-new-feature.md
  docs/docs/setup-guides/07_override-environment-properties.md
  serverless-functions/src/functions/common/twilio-wrappers/programmable-voice.private.js
  serverless-functions/src/functions/features/callback-and-voicemail/flex/fetch-voicemail.js
Labels: ready-for-review

#283 Add docs checks workflow
  .github/workflows/docs_checks.yaml
  docs/docs/how-it-works/00_overview.md
  docs/docs/how-it-works/01_docs.md
  docs/docs/how-it-works/02_flex-config.md
  docs/docs/how-it-works/03_infra-as-code.md
  docs/docs/how-it-works/09_github.md
Labels: ready-for-review

#285 Update es-es translation
  plugin-flex-ts-template-v2/src/feature-library/keyboard-shortcuts/flex-hooks/strings/es-es.json
  plugin-flex-ts-template-v2/src/feature-library/park-interaction/flex-hooks/strings/es-es.json
Labels: ready-for-review

#286 Skip docs checks if docs deploy disabled
  .github/workflows/docs_checks.yaml
Labels: ready-for-review

#280 Fix freeze from dual-channel feature during accept
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/flex-hooks/events/taskAccepted.ts
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/dualChannelHelper.ts
Labels: ready-for-review

#288 Fix canned responses enabled in Teams view
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/CannedResponsesDropdown.tsx
Labels: ready-for-review

#289 Fix scrolling in the tasks canvas when small
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/custom-components/ParticipantsTab/ParticipantsTab.tsx
  plugin-flex-ts-template-v2/src/feature-library/dispositions/custom-components/DispositionTab/DispositionTab.tsx
Labels: ready-for-review

#284 Clarify valid environment names in docs
  docs/docs/setup-guides/00_deploy-to-hosted-flex.md
Labels: documentation, ready-for-review

#291 Adding teams view columns
  docs/docs/feature-library/00_overview.md
  docs/docs/feature-library/teams-view-enhancements.md
  docs/static/img/features/teams-view-enhancements/teams-view-columns.png
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/config.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/flex-hooks/components/TeamsViewColumns.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/flex-hooks/strings/index.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/index.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-enhancements/types/ServiceConfiguration.ts
Labels: ready-for-review

#292 Fix CSS merge
  plugin-flex-ts-template-v2/src/utils/feature-loader/css-overrides.ts
Labels: bug, ready-for-review

#293 Fix recording after multiple transfers to worker
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/dualChannelHelper.ts
Labels: ready-for-review

#294 Docs styling improvements
  README.md
  docs/docs/feature-library/00_overview.md
  docs/docs/feature-library/admin-ui.md
  docs/docs/intro.mdx
  docs/docs/setup-guides/01_local-setup-and-use.md
  docs/docusaurus.config.js
  docs/package.json
  docs/src/css/custom.scss
  docs/static/img/logos/flex-text-darkmode.png
  docs/static/img/logos/flex-text-lightmode.png
  docs/static/img/logos/flex.png
  docs/static/img/twilio.png
Labels: documentation, ready-for-review

#296 Retry upon common network errors
  plugin-flex-ts-template-v2/src/utils/serverless/ApiService/index.ts
  serverless-functions/src/functions/common/helpers/retry-handler.private.js
Labels: ready-for-review

#295 Reservation handler bug
  docs/docs/feature-library/activity-reservation-handler.md
  docs/docusaurus.config.js
  docs/package.json
  docs/static/img/features/activity-reservation-handler/activty-reservation-handler.gif
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/config.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/custom-components/pending-activity/PendingActivityComponent.tsx
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/CompleteTask.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/SelectTask.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/SetActivity.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/SetWorkerActivity.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/StartOutboundCall.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskAccepted.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskCanceled.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskCompleted.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskReceived.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskRejected.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskRescinded.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskTimeout.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/taskWrapup.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/workerActivityUpdated.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/notifications/ActivityReservationHandler.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/strings/ActivityReservationHandler.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/helper/ActivityManager.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/helpers/flexHelper.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/helpers/pendingActivity.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/helpers/systemActivities.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/helpers/taskEndedHandler.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/helpers/workerActivityHelper.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/types/PendingActivity.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/types/feature-loader/FlexEvent.ts
  plugin-flex-ts-template-v2/src/utils/feature-loader/events.ts
  plugin-flex-ts-template-v2/src/utils/flex-helper/index.ts
  plugin-flex-ts-template-v2/src/utils/index-query/InstantQueryHelper/index.ts
  plugin-flex-ts-template-v2/src/utils/index-query/InstantQueryHelper/types.ts
  plugin-flex-ts-template-v2/src/utils/index-query/LiveQueryHelper/index.ts
  plugin-flex-ts-template-v2/src/utils/index-query/LiveQueryHelper/types.ts
Labels: bug, ready-for-review

#297 Making variables available for terraform studio functions
  .github/actions/terraform_state_artifact/action.yml
  infra-as-code/terraform/environments/default/main.tf
  infra-as-code/terraform/environments/default/variables.tf
  infra-as-code/terraform/modules/studio/main.tf
  infra-as-code/terraform/modules/studio/variables.tf
  infra-as-code/terraform/studio/voice-flow.json
Labels: ready-for-review

#300 updating documentation
  docs/docs/feature-library/activity-reservation-handler.md
Labels: ready-for-review

#304 Reservation bug 02
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/SetActivity.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/actions/SetWorkerActivity.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/helper/ActivityManager.ts
Labels: bug, ready-for-review

#305 Pin some dependencies to fix TR SDK types issue
  plugin-flex-ts-template-v2/package.json
Labels: bug, ready-for-review, dependencies

#302 Updating docs
  docs/docs/feature-library/activity-reservation-handler.md
  docs/docs/setup-guides/00_deploy-to-hosted-flex.md
  docs/docs/setup-guides/07_configure_the_template.md
  docs/docs/setup-guides/07_override-environment-properties.md
  docs/static/img/guides/github-override-config.png
Labels: ready-for-review
