Repository twilio-professional-services/flex-project-template, pull requests merged in 2023-04, with the labels that each got.

#175 Fix lint issues in the readme example code
  plugin-flex-ts-template-v2/README.md
  plugin-flex-ts-template-v2/template-files/feature-template/index.ts
Labels: ready-for-review

#172 Fix v2 tests and add to CI, fix v1 readme links
  .github/workflows/check_plugin_v2.yaml
  README.md
  plugin-flex-ts-template-v2/__mocks__/@twilio/flex-ui.js
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/setupTests.js
  plugin-flex-ts-template-v2/src/utils/serverless/ApiService/ApiService.test.ts
  plugin-flex-ts-template-v2/test-utils/flex-redux.ts
  plugin-flex-ts-template-v2/test-utils/flex-service-configuration.ts
Labels: ready-for-review

#177 Add eslint to serverless-functions
  .github/workflows/check_serverless.yaml
  README.md
  serverless-functions/.prettierrc.js
  serverless-functions/package.json
  serverless-functions/src/functions/common/flex/phone-numbers/list-phone-numbers.js
  serverless-functions/src/functions/common/flex/programmable-chat/update-channel-attributes.js
  serverless-functions/src/functions/common/flex/programmable-voice/add-participant.js
  serverless-functions/src/functions/common/flex/programmable-voice/cold-transfer.js
  serverless-functions/src/functions/common/flex/programmable-voice/get-call-properties.js
  serverless-functions/src/functions/common/flex/programmable-voice/hold-participant.js
  serverless-functions/src/functions/common/flex/programmable-voice/remove-participant.js
  serverless-functions/src/functions/common/flex/programmable-voice/update-participant.js
  serverless-functions/src/functions/common/flex/taskrouter/get-queues.js
  serverless-functions/src/functions/common/flex/taskrouter/get-worker-channels.js
  serverless-functions/src/functions/common/flex/taskrouter/update-task-assignment-status.js
  serverless-functions/src/functions/common/flex/taskrouter/update-task-attributes.js
  serverless-functions/src/functions/common/flex/taskrouter/update-worker-channel.js
  serverless-functions/src/functions/common/helpers/parameter-validator.private.js
  serverless-functions/src/functions/common/helpers/prepare-function.private.js
  serverless-functions/src/functions/common/twilio-wrappers/conference-participant.private.js
  serverless-functions/src/functions/common/twilio-wrappers/interactions.private.js
  serverless-functions/src/functions/common/twilio-wrappers/phone-numbers.private.js
  serverless-functions/src/functions/common/twilio-wrappers/programmable-chat.private.js
  serverless-functions/src/functions/common/twilio-wrappers/programmable-voice.private.js
  serverless-functions/src/functions/common/twilio-wrappers/retry-handler.private.js
  serverless-functions/src/functions/common/twilio-wrappers/sync.private.js
  serverless-functions/src/functions/common/twilio-wrappers/taskrouter.private.js
  serverless-functions/src/functions/features/callback-and-voicemail/common/callback-operations.private.js
  serverless-functions/src/functions/features/callback-and-voicemail/flex/create-callback.js
  serverless-functions/src/functions/features/callback-and-voicemail/studio/create-callback.protected.js
  serverless-functions/src/functions/features/callback-and-voicemail/studio/wait-experience.protected.js
  serverless-functions/src/functions/features/chat-to-video-escalation/agent-get-token.js
  serverless-functions/src/functions/features/chat-to-video-escalation/client-get-sync-token.js
  serverless-functions/src/functions/features/chat-to-video-escalation/client-get-video-token.js
  serverless-functions/src/functions/features/chat-to-video-escalation/generate-unique-code.js
  serverless-functions/src/functions/features/chat-transfer/common/chat-operations.private.js
  serverless-functions/src/functions/features/chat-transfer/flex/complete-task-for-transfer.js
  serverless-functions/src/functions/features/chat-transfer/flex/create-transfer-task.js
  serverless-functions/src/functions/features/chat-transfer/studio/add-task-to-chat-channel-data.protected.js
  serverless-functions/src/functions/features/conversation-transfer/flex/invite-participant.js
  serverless-functions/src/functions/features/conversation-transfer/flex/remove-participant.js
  serverless-functions/src/functions/features/dual-channel-recording/flex/create-recording.js
  serverless-functions/src/functions/features/hang-up-by/flex/fetch-conference-participant.js
  serverless-functions/src/functions/features/internal-call/common/agent-join-conference.protected.js
  serverless-functions/src/functions/features/internal-call/common/agent-outbound-join.protected.js
  serverless-functions/src/functions/features/internal-call/common/call-outbound-join.protected.js
  serverless-functions/src/functions/features/internal-call/flex/cleanup-rejected-task.js
  serverless-functions/src/functions/features/pause-recording/flex/pause-call-recording.js
  serverless-functions/src/functions/features/pause-recording/flex/pause-conference-recording.js
  serverless-functions/src/functions/features/pause-recording/flex/resume-call-recording.js
  serverless-functions/src/functions/features/pause-recording/flex/resume-conference-recording.js
  serverless-functions/src/functions/features/queue-stats-and-metadata/refresh-stats.protected.js
  serverless-functions/src/functions/features/supervisor-barge-coach/flex/participant-mute-and-coach.js
  serverless-functions/src/functions/features/supervisor-complete-reservation/flex/update-reservation.js
Labels: ready-for-review

#179 add optional chanining
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/supervisor-barge-coach/helpers/supervisorAlertHelper.ts
Labels: ready-for-review

#181 Add eslint to serverless-schedule-manager
  .github/workflows/check_schedule_manager.yaml
  README.md
  serverless-schedule-manager/.prettierrc.js
  serverless-schedule-manager/functions/admin/list.js
  serverless-schedule-manager/functions/admin/publish.js
  serverless-schedule-manager/functions/admin/update-status.js
  serverless-schedule-manager/functions/admin/update.js
  serverless-schedule-manager/functions/check-schedule.js
  serverless-schedule-manager/functions/common/helpers/parameter-validator.private.js
  serverless-schedule-manager/functions/common/helpers/prepare-function.private.js
  serverless-schedule-manager/functions/common/helpers/schedule-utils.private.js
  serverless-schedule-manager/functions/common/twilio-wrappers/retry-handler.private.js
  serverless-schedule-manager/functions/common/twilio-wrappers/serverless.private.js
  serverless-schedule-manager/package.json
Labels: ready-for-review

#180 Chat Canned Responses feature
  README.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/README.md
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/README.md
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/config.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/CannedResponsesCRM.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Category/Category.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Category/index.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Response/Response.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Response/index.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/index.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/CannedResponsesDropdown.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/index.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/components/CRMContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/components/MessageInputActions.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/paste-elements/index.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/index.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/screenshots/CRMPanel-UI.gif
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/screenshots/MessageInputAction-UI.gif
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/types/CannedResponses.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/utils/CannedResponsesService.ts
  plugin-flex-ts-template-v2/src/types/feature-loader/FlexComponent.ts
  serverless-functions/src/assets/features/canned-responses/responses.private.json
  serverless-functions/src/functions/features/canned-responses/flex/chat-responses.js
Labels: ready-for-review

#183 Fix several CI and linter issues
  .github/workflows/bump_version_plugin_v1.yaml
  .github/workflows/bump_version_plugin_v2.yaml
  .github/workflows/check_plugin_v2.yaml
  .github/workflows/check_serverless.yaml
  .github/workflows/checks.yaml
  .gitignore
  README.md
  package.json
  plugin-flex-ts-template-v2/.eslintrc.js
  plugin-flex-ts-template-v2/.prettierignore
  plugin-flex-ts-template-v2/package.json
  scripts/common.js
  scripts/setup-local-environment.js
  serverless-functions/.eslintrc.js
  serverless-functions/package.json
  serverless-schedule-manager/.eslintrc.js
  serverless-schedule-manager/package.json
Labels: ready-for-review

#184 Fix version bump branch
  .github/workflows/bump_version_plugin_v2.yaml
Labels: ready-for-review

#185 Fix manual trigger of version bump
  .github/workflows/bump_version_plugin_v1.yaml
  .github/workflows/bump_version_plugin_v2.yaml
  plugin-flex-ts-template-v2/package.json
Labels: ready-for-review

#189 Fix the example web app's environment variable usage to allow Serverless Functions to be called from the Next JS app
  web-app-examples/video-app-quickstart/.env.example
  web-app-examples/video-app-quickstart/README.md
  web-app-examples/video-app-quickstart/components/VideoRoom/VideoRoom.tsx
Labels: ready-for-review

#190 Rely on automatic versioning by the Flex Plugins CLI
  .github/workflows/bump_version_plugin_v1.yaml
  .github/workflows/bump_version_plugin_v2.yaml
  README.md
  package.json
  plugin-flex-ts-template-v1/package.json
  plugin-flex-ts-template-v2/package.json
Labels: ready-for-review

#193 Workaround Flex bug in dual channel recording
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/dualChannelHelper.ts
Labels: ready-for-review

#194 Replace teams-view-filters multiselect component
  plugin-flex-ts-template-v2/.eslintrc.js
  plugin-flex-ts-template-v2/package.json
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/custom-components/SelectFilter/SelectFilter.tsx
Labels: enhancement, ready-for-review

#195 Fix queueNoWorkerDataFilter display by using Redux
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/custom-components/SelectFilter/SelectFilter.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/flex-hooks/actions/beforeApplyTeamsViewFilters.ts
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/flex-hooks/states/QueueNoWorkerDataFilterSlice.ts
Labels: ready-for-review

#198 Fix canned responses with programmable chat
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Response/Response.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/CannedResponsesDropdown.tsx
Labels: ready-for-review

#197 Dynamic max capacity in omni-channel-capacity-management feature
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/omni-channel-capacity-management/README.md
  plugin-flex-ts-template-v2/src/feature-library/omni-channel-capacity-management/config.ts
  plugin-flex-ts-template-v2/src/feature-library/omni-channel-capacity-management/flex-hooks/actions/AcceptTask.ts
  plugin-flex-ts-template-v2/src/feature-library/omni-channel-capacity-management/types/ServiceConfiguration.ts
Labels: ready-for-review

#199 Canned responses improvements
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesCRM/Response/Response.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/custom-components/CannedResponsesDropdown/CannedResponsesDropdown.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/flex-hooks/components/CRMContainer.tsx
  plugin-flex-ts-template-v2/src/feature-library/canned-responses/utils/CannedResponsesService.ts
Labels: ready-for-review

#202 add-feature script improvements
  plugin-flex-ts-template-v2/template-files/feature-template/config.ts
  scripts/add-feature.js
Labels: bug, ready-for-review

#196 Expose error response status from ApiService
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/flex-hooks/strings/ScheduleManager.ts
  plugin-flex-ts-template-v2/src/feature-library/schedule-manager/utils/ScheduleManagerService.ts
  plugin-flex-ts-template-v2/src/utils/serverless/ApiService/index.ts
Labels: ready-for-review

#204 Use pluginsInitialized instead of pluginsLoaded
  plugin-flex-ts-template-v2/README.md
  plugin-flex-ts-template-v2/src/feature-library/activity-reservation-handler/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/conversation-transfer/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/feature-library/multi-call/flex-hooks/events/pluginsInitialized.ts
  plugin-flex-ts-template-v2/src/types/feature-loader/FlexEvent.ts
  plugin-flex-ts-template-v2/src/utils/feature-loader/events.ts
Labels: bug, ready-for-review

#201 Add dispositions feature
  README.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/README.md
  plugin-flex-ts-template-v2/src/feature-library/agent-automation/README.md
  plugin-flex-ts-template-v2/src/feature-library/dispositions/README.md
  plugin-flex-ts-template-v2/src/feature-library/dispositions/config.ts
  plugin-flex-ts-template-v2/src/feature-library/dispositions/custom-components/DispositionTab/DispositionTab.tsx
  plugin-flex-ts-template-v2/src/feature-library/dispositions/custom-components/DispositionTab/index.ts
  plugin-flex-ts-template-v2/src/feature-library/dispositions/flex-hooks/actions/CompleteTask.ts
  plugin-flex-ts-template-v2/src/feature-library/dispositions/flex-hooks/components/TaskCanvasTabs.tsx
  plugin-flex-ts-template-v2/src/feature-library/dispositions/flex-hooks/notifications/index.ts
  plugin-flex-ts-template-v2/src/feature-library/dispositions/flex-hooks/states/index.ts
  plugin-flex-ts-template-v2/src/feature-library/dispositions/flex-hooks/strings/index.ts
  plugin-flex-ts-template-v2/src/feature-library/dispositions/index.ts
  plugin-flex-ts-template-v2/src/feature-library/dispositions/screenshots/dispositions.gif
  plugin-flex-ts-template-v2/src/feature-library/dispositions/types/ServiceConfiguration.ts
  plugin-flex-ts-template-v2/src/feature-library/dual-channel-recording/helpers/dualChannelHelper.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/flex-hooks/actions/CompleteTask.ts
  plugin-flex-ts-template-v2/src/feature-library/hang-up-by/helpers/hangUpBy.ts
  plugin-flex-ts-template-v2/src/utils/feature-loader/index.ts
  plugin-flex-ts-template-v2/src/utils/serverless/TaskRouter/CompleteTask.ts
  plugin-flex-ts-template-v2/src/utils/serverless/TaskRouter/TaskRouterService.ts
Labels: ready-for-review
