Repository twilio-professional-services/flex-project-template, pull requests merged in 2023-08, with the labels that each got.

#308 Add schedule check to terraform voice flow
  infra-as-code/terraform/studio/voice-flow.json
Labels: enhancement, ready-for-review

#313 Update the updates doc
  docs/docs/setup-guides/05_managing-future-updates-from-the-template.md
Labels: documentation, ready-for-review

#312 Updating activity skill filter
  docs/docs/feature-library/activity-reservation-handler.md
  docs/docs/feature-library/activity-skill-filter.md
  docs/static/img/features/activity-skill-filter/feature-disabled.png
  docs/static/img/features/activity-skill-filter/feature-enabled.png
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/activity-wrapper/ActivityWrapper.ts
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/custom-components/worker-profile-info/WorkerProfileInfo.tsx
  plugin-flex-ts-template-v2/src/feature-library/activity-skill-filter/utils/AgentActivities.ts
Labels: ready-for-review

#301 Dynamic feature removal script
  .github/template_files/checks.yaml
  .github/template_files/flex_deploy.yaml
  .github/workflows/checks.yaml
  .github/workflows/flex_deploy.yaml
  docs/docs/setup-guides/00_deploy-to-hosted-flex.md
  docs/docs/setup-guides/01_local-setup-and-use.md
  docs/docs/setup-guides/02_deploy-to-flex-manual.md
  docs/docs/setup-guides/03_standalone-plugin-usage.md
  docs/docs/setup-guides/04_managing-future-updates-from-the-template.md
  docs/docs/setup-guides/05_add-new-feature.md
  docs/docs/setup-guides/06_removing-features.md
  flex-config/template-files/ui_attributes.common.json
  flex-config/template-files/ui_attributes.example.json
  scripts/common.js
  scripts/populate-missing-placeholders.js
  scripts/remove-features.js
  scripts/setup-local-environment.js
Labels: ready-for-review

#314 Clarify appConfig.js initial setup in docs
  docs/docs/setup-guides/07_configure_the_template.md
Labels: documentation, ready-for-review

#315 Adding activities to terraform
  .github/actions/terraform_state_artifact/action.yml
  infra-as-code/terraform/modules/taskrouter/activities.tf
Labels: ready-for-review

#317 Fix error logged during initial setup
  scripts/common.js
Labels: ready-for-review

#327 Allow Windows line endings in Prettier
  plugin-flex-ts-template-v2/.eslintrc.js
  serverless-functions/.eslintrc.js
  serverless-schedule-manager/.eslintrc.js
Labels: ready-for-review

#326 Improve copy-ability from the merge updates doc
  docs/docs/setup-guides/04_managing-future-updates-from-the-template.md
Labels: documentation, ready-for-review

#331 Improve terraform script reliability
  .github/actions/terraform_state_artifact/action.yml
Labels: bug, ready-for-review

#329 Add input select option to device-manager
  docs/docs/feature-library/device-manager.md
  flex-config/ui_attributes.common.json
  plugin-flex-ts-template-v2/src/feature-library/device-manager/config.ts
  plugin-flex-ts-template-v2/src/feature-library/device-manager/custom-components/DeviceManager/DeviceManager.tsx
  plugin-flex-ts-template-v2/src/feature-library/device-manager/flex-hooks/strings/index.ts
  plugin-flex-ts-template-v2/src/feature-library/device-manager/types/ServiceConfiguration.ts
Labels: ready-for-review

#322 Refactor environment setup
  .github/workflows/flex_deploy.yaml
  flex-config/.env.example
  flex-config/index.js
  flex-config/ui_attributes.example.json
  package.json
  scripts/add-feature.mjs
  scripts/common.js
  scripts/common/constants.mjs
  scripts/common/fetch-cli.mjs
  scripts/common/fill-replacements.mjs
  scripts/common/get-account.mjs
  scripts/common/get-plugin.mjs
  scripts/common/install-packages.mjs
  scripts/common/print-replacements.mjs
  scripts/common/save-appconfig.mjs
  scripts/populate-missing-placeholders.js
  scripts/remove-features.mjs
  scripts/rename-template.js
  scripts/rename-template.mjs
  scripts/select-plugin.js
  scripts/setup-environment.mjs
  scripts/setup-local-environment.js
  scripts/show-env-vars.js
  serverless-functions/.env.example
  serverless-schedule-manager/.env.example
  serverless-schedule-manager/package.json
  serverless-schedule-manager/scripts/fetch-config.mjs
  web-app-examples/video-app-quickstart/.env.example
  web-app-examples/video-app-quickstart/README.md
  web-app-examples/video-app-quickstart/components/VideoRoom/VideoRoom.tsx
Labels: ready-for-review

#334 Teams view filters fixes
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/custom-components/SelectFilter/SelectFilter.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/custom-components/SelectFilterLabel/SelectFilterLabel.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/agentSkillsFilter.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/queueNoWorkerDataFilter.tsx
  plugin-flex-ts-template-v2/src/feature-library/teams-view-filters/filters/queueWorkerDataFilter.tsx
  plugin-flex-ts-template-v2/src/utils/feature-loader/teams-filters.ts
Labels: bug, ready-for-review
